<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => 'b27e8c542bdc4d7ffcd41029a6b07e0d',
  'DATABASE_URL' => 'sqlite:///%kernel.project_dir%/var/data.db',
  'SENTRY_DSN' => 'https://69b4acf880144cb4afa6c94014514802@o569018.ingest.sentry.io/5714459',
  'appVersion' => '2.1.2',
  'dbservername' => 'localhost',
  'dbdatabase' => 'betting_dev',
  'dbusername' => 'root',
  'dbpassword' => 'Klzeprobe123!',
  'mysqliWorkersNumber' => '6',
  'httpWorkersNumber' => '6',
  'oddsThreshold' => '3',
  'timerHandicapMultiplier' => '0.0007',
  'positionPercentage' => '40',
  'handicapModifier' => '0.025',
  'appUrl' => 'http://dev.horseprediction.com'
);
