<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'b27e8c542bdc4d7ffcd41029a6b07e0d',
  'DATABASE_URL' => 'sqlite:///%kernel.project_dir%/var/data.db',
  'SENTRY_DSN' => 'https://69b4acf880144cb4afa6c94014514802@o569018.ingest.sentry.io/5714459',
  'appVersion' => '2.3.1',
  'dbservername' => 'localhost',
  'dbdatabase' => 'betting',
  'dbusername' => 'app',
  'dbpassword' => 'PoliteBison11#22',
  'mysqliWorkersNumber' => '100',
  'httpWorkersNumber' => '100',
  'oddsThreshold' => '3',
  'timerHandicapMultiplier' => '0.025',
  'positionPercentage' => '55',
  'handicapModifier' => '5.000',
  'appUrl' => 'http://horseprediction.com',
);
